/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class baldzarika_ucv_test_UCVActivity_ConfigChooser */

#ifndef _Included_baldzarika_ucv_test_UCVActivity_ConfigChooser
#define _Included_baldzarika_ucv_test_UCVActivity_ConfigChooser
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
