/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_baldzarika_ar_fiducial_BCHMarkerModel */

#ifndef _Included_com_baldzarika_ar_fiducial_BCHMarkerModel
#define _Included_com_baldzarika_ar_fiducial_BCHMarkerModel
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_baldzarika_ar_fiducial_BCHMarkerModel
 * Method:    create
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_baldzarika_ar_fiducial_BCHMarkerModel_create
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
