/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_baldzarika_ar_fiducial_Detector */

#ifndef _Included_com_baldzarika_ar_fiducial_Detector
#define _Included_com_baldzarika_ar_fiducial_Detector
#ifdef __cplusplus
extern "C" {
#endif
#undef com_baldzarika_ar_fiducial_Detector_RS_STOPPED
#define com_baldzarika_ar_fiducial_Detector_RS_STOPPED 0L
#undef com_baldzarika_ar_fiducial_Detector_RS_STARTING
#define com_baldzarika_ar_fiducial_Detector_RS_STARTING 1L
#undef com_baldzarika_ar_fiducial_Detector_RS_STARTED
#define com_baldzarika_ar_fiducial_Detector_RS_STARTED 2L
#undef com_baldzarika_ar_fiducial_Detector_RS_STOPPING
#define com_baldzarika_ar_fiducial_Detector_RS_STOPPING 3L
/*
 * Class:     com_baldzarika_ar_fiducial_Detector
 * Method:    create
 * Signature: (Lcom/baldzarika/ar/Size2;)V
 */
JNIEXPORT void JNICALL Java_com_baldzarika_ar_fiducial_Detector_create
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_baldzarika_ar_fiducial_Detector
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_baldzarika_ar_fiducial_Detector_destroy
  (JNIEnv *, jobject);

/*
 * Class:     com_baldzarika_ar_fiducial_Detector
 * Method:    addMarkerModel
 * Signature: (Lcom/baldzarika/ar/fiducial/MarkerModel;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_baldzarika_ar_fiducial_Detector_addMarkerModel
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_baldzarika_ar_fiducial_Detector
 * Method:    removeMarkerModel
 * Signature: (Lcom/baldzarika/ar/fiducial/MarkerModel;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_baldzarika_ar_fiducial_Detector_removeMarkerModel
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_baldzarika_ar_fiducial_Detector
 * Method:    start
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_baldzarika_ar_fiducial_Detector_start
  (JNIEnv *, jobject);

/*
 * Class:     com_baldzarika_ar_fiducial_Detector
 * Method:    isActive
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_baldzarika_ar_fiducial_Detector_isActive
  (JNIEnv *, jobject);

/*
 * Class:     com_baldzarika_ar_fiducial_Detector
 * Method:    isStarting
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_baldzarika_ar_fiducial_Detector_isStarting
  (JNIEnv *, jobject);

/*
 * Class:     com_baldzarika_ar_fiducial_Detector
 * Method:    isStarted
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_baldzarika_ar_fiducial_Detector_isStarted
  (JNIEnv *, jobject);

/*
 * Class:     com_baldzarika_ar_fiducial_Detector
 * Method:    stop
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_baldzarika_ar_fiducial_Detector_stop
  (JNIEnv *, jobject);

/*
 * Class:     com_baldzarika_ar_fiducial_Detector
 * Method:    waitToStop
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_baldzarika_ar_fiducial_Detector_waitToStop
  (JNIEnv *, jobject);

/*
 * Class:     com_baldzarika_ar_fiducial_Detector
 * Method:    update
 * Signature: ([BI)Z
 */
JNIEXPORT jboolean JNICALL Java_com_baldzarika_ar_fiducial_Detector_update
  (JNIEnv *, jobject, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
