/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_baldzarika_ar_Tracker_MarkerStateCallback */

#ifndef _Included_com_baldzarika_ar_Tracker_MarkerStateCallback
#define _Included_com_baldzarika_ar_Tracker_MarkerStateCallback
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
