/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_baldzarika_ar_fiducial_MarkerModel */

#ifndef _Included_com_baldzarika_ar_fiducial_MarkerModel
#define _Included_com_baldzarika_ar_fiducial_MarkerModel
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_baldzarika_ar_fiducial_MarkerModel
 * Method:    initialize
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_baldzarika_ar_fiducial_MarkerModel_initialize
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_baldzarika_ar_fiducial_MarkerModel
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_baldzarika_ar_fiducial_MarkerModel_destroy
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
