/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_baldzarika_ar_markerless_Tracker */

#ifndef _Included_com_baldzarika_ar_markerless_Tracker
#define _Included_com_baldzarika_ar_markerless_Tracker
#ifdef __cplusplus
extern "C" {
#endif
#undef com_baldzarika_ar_markerless_Tracker_RS_STOPPED
#define com_baldzarika_ar_markerless_Tracker_RS_STOPPED 0L
#undef com_baldzarika_ar_markerless_Tracker_RS_STARTING
#define com_baldzarika_ar_markerless_Tracker_RS_STARTING 1L
#undef com_baldzarika_ar_markerless_Tracker_RS_STARTED
#define com_baldzarika_ar_markerless_Tracker_RS_STARTED 2L
#undef com_baldzarika_ar_markerless_Tracker_RS_STOPPING
#define com_baldzarika_ar_markerless_Tracker_RS_STOPPING 3L
/*
 * Class:     com_baldzarika_ar_markerless_Tracker
 * Method:    create
 * Signature: (Lcom/baldzarika/ar/Size2;)J
 */
JNIEXPORT jlong JNICALL Java_com_baldzarika_ar_markerless_Tracker_create
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_baldzarika_ar_markerless_Tracker
 * Method:    addMarker
 * Signature: (Lcom/baldzarika/ar/markerless/Marker;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_baldzarika_ar_markerless_Tracker_addMarker
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_baldzarika_ar_markerless_Tracker
 * Method:    removeMarker
 * Signature: (Lcom/baldzarika/ar/markerless/Marker;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_baldzarika_ar_markerless_Tracker_removeMarker
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
