APP_CPPFLAGS	+=	-DANDROID \
					-D__ANDROID__ \
					-DBOOST_THREAD_LINUX \
					-DBOOST_HAS_PTHREADS \
					-D_REENTRANT \
					-D_GLIBCXX__PTHREADS \
					-DBOOST_HAS_GETTIMEOFDAY \
					-DBOOST_NO_INTRINSIC_WCHAR_T \
					-DHAVE_GLES2
					
