/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_baldzarika_ar_Tracker */

#ifndef _Included_com_baldzarika_ar_Tracker
#define _Included_com_baldzarika_ar_Tracker
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_baldzarika_ar_Tracker
 * Method:    create
 * Signature: (Lcom/baldzarika/ar/Size2;)V
 */
JNIEXPORT void JNICALL Java_com_baldzarika_ar_Tracker_create
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_baldzarika_ar_Tracker
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_baldzarika_ar_Tracker_destroy
  (JNIEnv *, jobject);

/*
 * Class:     com_baldzarika_ar_Tracker
 * Method:    getFrameSize
 * Signature: ()Lcom/baldzarika/ar/Size2;
 */
JNIEXPORT jobject JNICALL Java_com_baldzarika_ar_Tracker_getFrameSize
  (JNIEnv *, jobject);

/*
 * Class:     com_baldzarika_ar_Tracker
 * Method:    setFrameSize
 * Signature: (Lcom/baldzarika/ar/Size2;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_baldzarika_ar_Tracker_setFrameSize
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_baldzarika_ar_Tracker
 * Method:    addMarker
 * Signature: (Lcom/baldzarika/ar/Marker;)Lcom/baldzarika/ar/Tracker/MarkerState;
 */
JNIEXPORT jobject JNICALL Java_com_baldzarika_ar_Tracker_addMarker
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_baldzarika_ar_Tracker
 * Method:    start
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_baldzarika_ar_Tracker_start
  (JNIEnv *, jobject);

/*
 * Class:     com_baldzarika_ar_Tracker
 * Method:    isStarted
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_baldzarika_ar_Tracker_isStarted
  (JNIEnv *, jobject);

/*
 * Class:     com_baldzarika_ar_Tracker
 * Method:    stop
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_baldzarika_ar_Tracker_stop
  (JNIEnv *, jobject);

/*
 * Class:     com_baldzarika_ar_Tracker
 * Method:    update
 * Signature: (Lcom/baldzarika/ar/Frame;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_baldzarika_ar_Tracker_update
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
