/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_baldzarika_ar_fiducial_Detector_MarkerState */

#ifndef _Included_com_baldzarika_ar_fiducial_Detector_MarkerState
#define _Included_com_baldzarika_ar_fiducial_Detector_MarkerState
#ifdef __cplusplus
extern "C" {
#endif
#undef com_baldzarika_ar_fiducial_Detector_MarkerState_SC_DETECTION
#define com_baldzarika_ar_fiducial_Detector_MarkerState_SC_DETECTION 0L
#undef com_baldzarika_ar_fiducial_Detector_MarkerState_SC_POSE
#define com_baldzarika_ar_fiducial_Detector_MarkerState_SC_POSE 1L
/*
 * Class:     com_baldzarika_ar_fiducial_Detector_MarkerState
 * Method:    create
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_baldzarika_ar_fiducial_Detector_00024MarkerState_create
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_baldzarika_ar_fiducial_Detector_MarkerState
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_baldzarika_ar_fiducial_Detector_00024MarkerState_destroy
  (JNIEnv *, jobject);

/*
 * Class:     com_baldzarika_ar_fiducial_Detector_MarkerState
 * Method:    isDetected
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_baldzarika_ar_fiducial_Detector_00024MarkerState_isDetected
  (JNIEnv *, jobject);

/*
 * Class:     com_baldzarika_ar_fiducial_Detector_MarkerState
 * Method:    getMarkerId
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_baldzarika_ar_fiducial_Detector_00024MarkerState_getMarkerId
  (JNIEnv *, jobject);

/*
 * Class:     com_baldzarika_ar_fiducial_Detector_MarkerState
 * Method:    getMarkerModel
 * Signature: ()Lcom/baldzarika/ar/fiducial/MarkerModel;
 */
JNIEXPORT jobject JNICALL Java_com_baldzarika_ar_fiducial_Detector_00024MarkerState_getMarkerModel
  (JNIEnv *, jobject);

/*
 * Class:     com_baldzarika_ar_fiducial_Detector_MarkerState
 * Method:    getDetector
 * Signature: ()Lcom/baldzarika/ar/fiducial/Detector;
 */
JNIEXPORT jobject JNICALL Java_com_baldzarika_ar_fiducial_Detector_00024MarkerState_getDetector
  (JNIEnv *, jobject);

/*
 * Class:     com_baldzarika_ar_fiducial_Detector_MarkerState
 * Method:    getHomography
 * Signature: ()Landroid/graphics/Matrix;
 */
JNIEXPORT jobject JNICALL Java_com_baldzarika_ar_fiducial_Detector_00024MarkerState_getHomography
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
