/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_baldzarika_ar_Tracker */

#ifndef _Included_com_baldzarika_ar_Tracker
#define _Included_com_baldzarika_ar_Tracker
#ifdef __cplusplus
extern "C" {
#endif
#undef com_baldzarika_ar_Tracker_RS_STOPPED
#define com_baldzarika_ar_Tracker_RS_STOPPED 0L
#undef com_baldzarika_ar_Tracker_RS_STARTING
#define com_baldzarika_ar_Tracker_RS_STARTING 1L
#undef com_baldzarika_ar_Tracker_RS_STARTED
#define com_baldzarika_ar_Tracker_RS_STARTED 2L
#undef com_baldzarika_ar_Tracker_RS_STOPPING
#define com_baldzarika_ar_Tracker_RS_STOPPING 3L
/*
 * Class:     com_baldzarika_ar_Tracker
 * Method:    initialize
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_baldzarika_ar_Tracker_initialize
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_baldzarika_ar_Tracker
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_baldzarika_ar_Tracker_destroy
  (JNIEnv *, jobject);

/*
 * Class:     com_baldzarika_ar_Tracker
 * Method:    getFrameSize
 * Signature: ()Lcom/baldzarika/ar/Size2;
 */
JNIEXPORT jobject JNICALL Java_com_baldzarika_ar_Tracker_getFrameSize
  (JNIEnv *, jobject);

/*
 * Class:     com_baldzarika_ar_Tracker
 * Method:    setFrameSize
 * Signature: (Lcom/baldzarika/ar/Size2;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_baldzarika_ar_Tracker_setFrameSize
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_baldzarika_ar_Tracker
 * Method:    getCameraFovy
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_baldzarika_ar_Tracker_getCameraFovy
  (JNIEnv *, jobject);

/*
 * Class:     com_baldzarika_ar_Tracker
 * Method:    setCameraFovy
 * Signature: (F)Z
 */
JNIEXPORT jboolean JNICALL Java_com_baldzarika_ar_Tracker_setCameraFovy
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_baldzarika_ar_Tracker
 * Method:    getCameraZNear
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_baldzarika_ar_Tracker_getCameraZNear
  (JNIEnv *, jobject);

/*
 * Class:     com_baldzarika_ar_Tracker
 * Method:    setCameraZNear
 * Signature: (F)Z
 */
JNIEXPORT jboolean JNICALL Java_com_baldzarika_ar_Tracker_setCameraZNear
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_baldzarika_ar_Tracker
 * Method:    getCameraZFar
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_baldzarika_ar_Tracker_getCameraZFar
  (JNIEnv *, jobject);

/*
 * Class:     com_baldzarika_ar_Tracker
 * Method:    setCameraZFar
 * Signature: (F)Z
 */
JNIEXPORT jboolean JNICALL Java_com_baldzarika_ar_Tracker_setCameraZFar
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_baldzarika_ar_Tracker
 * Method:    getCameraFocalLength
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_baldzarika_ar_Tracker_getCameraFocalLength
  (JNIEnv *, jobject);

/*
 * Class:     com_baldzarika_ar_Tracker
 * Method:    getCameraProjection
 * Signature: ([F)Z
 */
JNIEXPORT jboolean JNICALL Java_com_baldzarika_ar_Tracker_getCameraProjection
  (JNIEnv *, jobject, jfloatArray);

/*
 * Class:     com_baldzarika_ar_Tracker
 * Method:    start
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_baldzarika_ar_Tracker_start
  (JNIEnv *, jobject);

/*
 * Class:     com_baldzarika_ar_Tracker
 * Method:    isActive
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_baldzarika_ar_Tracker_isActive
  (JNIEnv *, jobject);

/*
 * Class:     com_baldzarika_ar_Tracker
 * Method:    isStarting
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_baldzarika_ar_Tracker_isStarting
  (JNIEnv *, jobject);

/*
 * Class:     com_baldzarika_ar_Tracker
 * Method:    isStarted
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_baldzarika_ar_Tracker_isStarted
  (JNIEnv *, jobject);

/*
 * Class:     com_baldzarika_ar_Tracker
 * Method:    stop
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_baldzarika_ar_Tracker_stop
  (JNIEnv *, jobject);

/*
 * Class:     com_baldzarika_ar_Tracker
 * Method:    waitToStop
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_baldzarika_ar_Tracker_waitToStop
  (JNIEnv *, jobject);

/*
 * Class:     com_baldzarika_ar_Tracker
 * Method:    processFrame
 * Signature: ([BIII)Z
 */
JNIEXPORT jboolean JNICALL Java_com_baldzarika_ar_Tracker_processFrame
  (JNIEnv *, jobject, jbyteArray, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
