/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_baldzarika_ar_fiducial_Tracker_MarkerState */

#ifndef _Included_com_baldzarika_ar_fiducial_Tracker_MarkerState
#define _Included_com_baldzarika_ar_fiducial_Tracker_MarkerState
#ifdef __cplusplus
extern "C" {
#endif
#undef com_baldzarika_ar_fiducial_Tracker_MarkerState_SC_DETECTION
#define com_baldzarika_ar_fiducial_Tracker_MarkerState_SC_DETECTION 0L
#undef com_baldzarika_ar_fiducial_Tracker_MarkerState_SC_POSE
#define com_baldzarika_ar_fiducial_Tracker_MarkerState_SC_POSE 1L
#undef com_baldzarika_ar_fiducial_Tracker_MarkerState_SC_DETECT_NOTIFY
#define com_baldzarika_ar_fiducial_Tracker_MarkerState_SC_DETECT_NOTIFY 2L
/*
 * Class:     com_baldzarika_ar_fiducial_Tracker_MarkerState
 * Method:    getMarkerId
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_baldzarika_ar_fiducial_Tracker_00024MarkerState_getMarkerId
  (JNIEnv *, jobject);

/*
 * Class:     com_baldzarika_ar_fiducial_Tracker_MarkerState
 * Method:    getMarkerModel
 * Signature: ()Lcom/baldzarika/ar/fiducial/MarkerModel;
 */
JNIEXPORT jobject JNICALL Java_com_baldzarika_ar_fiducial_Tracker_00024MarkerState_getMarkerModel
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
