/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_baldzarika_ar_Frame */

#ifndef _Included_com_baldzarika_ar_Frame
#define _Included_com_baldzarika_ar_Frame
#ifdef __cplusplus
extern "C" {
#endif
#undef com_baldzarika_ar_Frame_PFMT_NV16
#define com_baldzarika_ar_Frame_PFMT_NV16 16L
#undef com_baldzarika_ar_Frame_PFMT_NV21
#define com_baldzarika_ar_Frame_PFMT_NV21 17L
/*
 * Class:     com_baldzarika_ar_Frame
 * Method:    create
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_baldzarika_ar_Frame_create__
  (JNIEnv *, jobject);

/*
 * Class:     com_baldzarika_ar_Frame
 * Method:    create
 * Signature: (Lcom/baldzarika/ar/Size2;)V
 */
JNIEXPORT void JNICALL Java_com_baldzarika_ar_Frame_create__Lcom_baldzarika_ar_Size2_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_baldzarika_ar_Frame
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_baldzarika_ar_Frame_destroy
  (JNIEnv *, jobject);

/*
 * Class:     com_baldzarika_ar_Frame
 * Method:    getSize
 * Signature: ()Lcom/baldzarika/ar/Size2;
 */
JNIEXPORT jobject JNICALL Java_com_baldzarika_ar_Frame_getSize
  (JNIEnv *, jobject);

/*
 * Class:     com_baldzarika_ar_Frame
 * Method:    getMedianPixelValue
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_com_baldzarika_ar_Frame_getMedianPixelValue
  (JNIEnv *, jobject);

/*
 * Class:     com_baldzarika_ar_Frame
 * Method:    setPixels
 * Signature: ([BI)Z
 */
JNIEXPORT jboolean JNICALL Java_com_baldzarika_ar_Frame_setPixels
  (JNIEnv *, jobject, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
